FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    g++ \
    && rm -rf /var/lib/apt/lists/*

COPY services/api-flask/requirements.txt .

RUN pip install --no-cache-dir torch==2.3.1 --index-url https://download.pytorch.org/whl/cpu

RUN pip install --no-cache-dir -r requirements.txt

COPY services/api-flask/ .

COPY pipelines/ ./pipelines/

EXPOSE 5000

CMD [ "gunicorn", "--bind", "0.0.0.0:5000", "run:app", "--reload" ]
