FROM python:3.12-slim

WORKDIR /app

COPY services/api-flask/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY services/api-flask/ .

COPY pipelines/ ./pipelines/

EXPOSE 5000

CMD [ "gunicorn", "--bind", "0.0.0.0:5000", "run:app", "--reload" ]
