"""add last_indexed_at to candidates

Revision ID: 5533abe98096
Revises: 91528de547ba
Create Date: 2026-02-02 20:49:02.262084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5533abe98096'
down_revision: Union[str, Sequence[str], None] = '91528de547ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('last_indexed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'last_indexed_at')
    # ### end Alembic commands ###
